### PR TITLE
Hopefully this shall take care of the issue reported here

### PR DESCRIPTION
**Pull request by RobertDober**
https://github.com/RobertDober/earmark_parser/pull/85#issuecomment-1031761529

### CODE REVIEW

**Comment by noozo** [comment]
Is this related to the surface catalogue not showing the components?

**Comment by RobertDober** [comment]
@noozo sorry but I am not aware of the context just fixed the bad call in my code base

**Comment by msaraiva** [comment]
Hi @RobertDober!

Unfortunately, this only works if the user sets `override: true` for `earmark_parser`:

```
{:earmark_parser, "1.4.18", override: true},
```

Otherwise, we get conflict with `ex_doc` when runing `mix deps.get`:

```
Failed to use "earmark_parser" (version 1.4.18) because
  earmark (version 1.4.20) requires == 1.4.18
  ex_doc (version 0.28.0) requires ~> 1.4.19
  mix.exs specifies 1.4.18
```

So it seems users will be forced to adjust the versions manually to get things working for some libs at the cost of potentially breaking other libs.

**Comment by RobertDober** [comment]
Hmm maybe you could go with `earmark 1.5.0-pre1 ~> earmark 1.4.21`  @msaraiva 
this might break your lists so

I try to get 1.5.0 out, but the ETA is not near unfortunately

**Comment by msaraiva** [comment]
> maybe you could go with `earmark 1.5.0-pre1 ~> earmark 1.4.21`

Hex would not allow us to release a `v0.4.0` depending on a `*-pre` version. I guess we'll have to stick with this version until `v1.5.0` is out. 

Actually, any project depending on the latest stable Earmark version (v1.14.20) will present the same problem when using recent versions of `ex_doc`, as the latter requires `~> 1.4.19` and the former only `v1.4.18`.

I'm closing this issue for now as there's nothing we can do code-wise on our side. The only workaround for now is for the user to explicitly set `earmark_parser` version to `1.4.18` with `override: true`.

**Comment by RobertDober** [comment]
> Hex would not allow us to release a `v0.4.0` depending on a `*-pre` version. I guess we'll have to stick with this version until `v1.5.0` is out.

That is why I would like to help out with Earmark 1.4.21 =>  Earmark Parser 1.4.22

**Comment by msaraiva** [comment]
Hey @RobertDober!

I've just updated Earmark to `1.4.21` with Earmark Parser `1.4.22` and it works perfectly. Thank you so much! ❤️

**Pull request closed without merging**
